"""Add new project fields

Revision ID: e247dc2275e7
Revises: 1dcc780350d2
Create Date: 2025-03-21 10:01:21.629456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e247dc2275e7'
down_revision = '1dcc780350d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('technologies', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('challenges', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('solution', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('repository', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('repository')
        batch_op.drop_column('solution')
        batch_op.drop_column('challenges')
        batch_op.drop_column('technologies')
        batch_op.drop_column('category')
        batch_op.drop_column('client')

    # ### end Alembic commands ###
